### ISSUE TITLE
 How to use the generated static library in examples?

### ISSUE THREAD

**Issue by HikariS97** [ultravideo/kvzRTP#1]
My operating system is Win10, and I have successfully compiled the kvzrtp and generate a static file libkvzrtp.a. But when I try to test the lib on example/simple/sending.cc, I'm confused of how to use it. 
I use Visual Studio 2019 and added kvzrtp/src as include path, qtcomplied/debug as library path, but When I complile the sending.cc, I got lots of errors. It's confusing that you offer linking method on Windows is -L<Path to libkvzrtp.a> -lkvzrtp -lpthread... It seems like the command is linking dll.

**Comment by altonen** [comment]
hello,
I strongly suggest you use qtcreator on windows for the time being. There is visual studio support on some level (though it's not public yet) but i haven't tested the code at all so I don't know how well it works.

I will push the new code to github and create qtcreator project file for the examples so that they are easier to use. I admit the linking instructions for windows may seem a little convoluted but here's an example on how to link against kvzrtp on windows: https://github.com/ultravideo/kvazzup/blob/master/Kvazzup.pro#L250

**Comment by fador** [comment]
Basically you need to .lib file to link it in visual studio (or just include the whole library in the project..). The .a library works only in the mingw build.
Hopefully we can get the experimental visual studio support pushed here soon, that should fix those errors, but it's not 100% tested as @altonen mentioned.

**Comment by HikariS97** [comment]
@altonen Thanks for your quick reply. I have read the marked .pro file. It's too difficult. I have tried to edit a .pro file. Still have errors, it seems the way to add static lib is still wrong. Can u give me some clear(for me) advices? 
The Path F:\kva\build-kvzrtp-Desktop_Qt_5_14_2_MinGW_64_bit-Debug\debug is where libkvzrtp.a generated, by QtCreator. And there are aslo many .o files in the same folder.
The Path F:\kva\kvzRTP\src is the subfoler of the repo.

Here's my .pro file:
`TEMPLATE = app
CONFIG += console c++11
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += \
        main.cpp
INCLUDEPATH += F:/kva/kvzRTP/src
win32: LIBS += F:/kva/build-kvzrtp-Desktop_Qt_5_14_2_MinGW_64_bit-Debug/debug/libkvzrtp.a`

**Comment by altonen** [comment]
hello,
there are two problems in your project file:
the includepath is wrong because kvzrtp uses includes like "#include <kvzrtp/lib.hh>". You can fix this by creating a following folder structure:

```
mkdir F:/kva/kvzrtp
mkdir F:/kva/kvzrtp/formats
cp F:/kva/kvzRTP/src/*.hh F:/kva/kvzrtp
cp F:/kva/kvzRTP/src/formats/*.hh F:/kva/kvzrtp/formats
```
and then setting INCLUDEPATH = F:/kva/kvzrtp

Try using the following for the library options:
```
LIBS += -LF:/kva/build-kvzrtp-Desktop_Qt_5_14_2_MinGW_64_bit-Debug/debug/ -lkvzrtp
```

These may work but if not, await my update. I will add a step by step guide on how to get the examples working. It's actually quite tedious and I have to figure out how to make it simpler

**Comment by altonen** [comment]
hello,
github now includes all the latest changes, including support for msvc.

I have also added instruction to examples/README.md about the examples. I was able to get sending.cc working on Windows 7 following them so they should describe the right things in right order.

Recap: first run the prepare.bat which creates two folders lib/ and include/. These folders should be in the same folder with benchmarks/, examples/ and src/. If not, the script was ran from wrong folder. The include directory contains folder kvzrtp which in turn contains the header files and a formats folder for format headers.

When you have compiled kvzrtp, copy the library file (libkvzrtp.a) from the Qt build directory to the lib/ directory at the root. For you, this would mean that you copy the file from F:/kva/build-kvzrtp-Desktop_Qt_5_14_2_MinGW_64_bit-Debug/debug/libkvzrtp.a to F:/kva/kvzRTP/lib

When that is done, open the example.pro file which contains the necessary instructions for building sending.cc. If you wish to try other example codes, just change sending.cc with the name of the file you want to test.

Then build and run example.pro. Note: the Qt build directory for example.pro MUST be in the same directory as lib/, include/, and benchmarks. It should've been created there automatically but if it's not there, you need to update the INCLUDEPATH and LIB variables in the example.pro to point to correct folders.

Remember that you must also have the posix threads available

**Comment by HikariS97** [comment]
@altonen 
Hi,
Thanks for your reply. I have followed your instruction, and got some errors. Perhaps, the right INCLUDEPATH is the parrent folder of kvzrtp. I tried F:/kva/kvzrtp, and errors "no such files" appeared.

Secondly, after INCLUDEPATH corrected, I got same errors like before.
![微信截图_20200416200350](https://user-images.githubusercontent.com/48763518/79454220-6a0f0e80-801d-11ea-8b0b-3ad29d130c11.png)
If I delete the line "LIB += ...", these errors also appear. I think the source of the errors is the configuration of static library generated.

By the way, I have tried complie kvzrtp on Ubuntu16.04, I got errors  in frame.hh about getrandom. the compiler can't find random.h by <sys/random.h> , so I changed it to </usr/include/linux/random.h>. Then another error, getrandom is not declared in this scope. I have searched on stackflows and someone got same error, and fixed it by using syscall(getrandom, ...).
I'm excited about your work, kvzrtp and kvazzup. If it's just some bugs of configuration but not some logical errors, I hope it could be fixed up as soon.

Thank you.

**Comment by altonen** [comment]
hello @HikariS97 ,
The errors your image shows seem valid. There was a lot of API changes a while back and create_writer/create_reader was replaced with create_stream. I'm not sure what the ULONG error is about. If you are still interested in trying, I'd recommend you to delete everything, reclone the repository, rebuild the library from scratch and follow steps I described in my last message. It should work out of the box

About that ubuntu error. It should be present because getrandom() was added in release 3.17 [0] and Ubuntu 16.04 had version 4.4 [1] of the kernel. Unfortunately I cannot help you with that because sys/random.h is present on my computer and looking at the provided documentation, it should be present on your computer too.

I'm quite certain these are just configuration errors because the library has been working on multiple OSs and computers. I've attached tree /f output of the correct folder structure. If all else fails, you can try to mimic that and it should work.
```
▒ ▒▒build-kvzrtp-Desktop_Qt_5_14_0_MinGW_64_bit-Debug
▒       libkvzrtp.a
▒
▒▒▒▒kvz-rtplib
    ▒▒▒▒build-example-Desktop_Qt_5_14_0_MinGW_64_bit-Debug
    ▒       .qmake.stash
    ▒       example.exe
    ▒       Makefile
    ▒       sending.o
    ▒
    ▒▒▒▒examples
    ▒       binding.cc
    ▒       example.pro
    ▒       example.pro.user
    ▒       prepare.bat
    ▒       README.md
    ▒       sending.cc
    ▒
    ▒▒▒▒include
    ▒   ▒▒▒▒kvzrtp
    ▒       ▒   clock.hh
    ▒       ▒   crypto.hh
    ▒       ▒   debug.hh
    ▒       ▒   dispatch.hh
    ▒       ▒   frame.hh
    ▒       ▒   hostname.hh
    ▒       ▒   lib.hh
    ▒       ▒   media_stream.hh
    ▒       ▒   mingw_inet.hh
    ▒       ▒   multicast.hh
    ▒       ▒   poll.hh
    ▒       ▒   queue.hh
    ▒       ▒   random.hh
    ▒       ▒   receiver.hh
    ▒       ▒   rtcp.hh
    ▒       ▒   rtp.hh
    ▒       ▒   runner.hh
    ▒       ▒   send.hh
    ▒       ▒   sender.hh
    ▒       ▒   session.hh
    ▒       ▒   socket.hh
    ▒       ▒   srtp.hh
    ▒       ▒   util.hh
    ▒       ▒   zrtp.hh
    ▒       ▒
    ▒       ▒▒▒▒formats
    ▒               generic.hh
    ▒               hevc.hh
    ▒               opus.hh
    ▒
    ▒▒▒▒lib
    ▒       libkvzrtp.a
    ▒
```

[0] http://man7.org/linux/man-pages/man2/getrandom.2.html
[1] https://wiki.ubuntu.com/XenialXerus/ReleaseNotes

**Comment by HikariS97** [comment]
I delete all files and redownload the repo, and success.
Maybe I have deleted some files accidentally. I remember that some .o files are not generated. e.g. session.o
I'm not sure. But as least, everything works fine now. Thanks very much for your help !

**Comment by altonen** [comment]
Good to hear, closing this issue
